### ISSUE TITLE
Problem retrieving data from indices located in "euro zone" or "worldwide"

### ISSUE THREAD

**Issue by gerardorc85** [alvarob96/investpy#53]
Hi Alvaro,

With the latest update, the function get_index_historical_data() works perfectly with sectors and subsector located almost everywhere but for some reason has problems retrieving data from the following "countries":

- euro zone
- woldwide

Any clue of what the reason can be? See function and error below, also an screenshot.

index = investpy.get_index_historical_data(index='STOXX Europe 600 Utilities',country='euro zone',from_date='01/01/1934',to_date='01/10/2019')

RuntimeError: ERR#0034: country euro zone not found, check if it is correct.

![image](https://user-images.githubusercontent.com/55779669/66274118-8581ab80-e87b-11e9-8e08-c8afcd3a2849.png)

Cheers,
Gerardo

**Comment by alvarob96** [comment]
There was a problem related to index country listing which did not include **euro zone** and **world**, so on an exception was raising since the package was not properly checking the country listing.

It was already solved and will be available in the next release really soon! Probably this week, once all the current errors/bugs are fixed, mainly the ones related with the issue #50. 

Thank you for your support! ⭐️

**Comment by GitHunter0** [comment]
Hey @alvarobartt , I'm still having the same issue with investpy version 1.0.

For example, this returns the error message "RuntimeError: ERR#0034: country euro zone not found, check if it is correct.": 
`investpy.get_index_recent_data(index='STOXX 600',  country='euro zone', order='ascending', interval='Daily')`

Is there a workaround? I hope so, investpy is a fantastic package.

**Comment by alvarobartt** [comment]
@marineanalytica @GitHunter0 Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:

**Comment by remimec** [comment]
This issue persists in investpy-1.0.7

**Comment by alvarobartt** [comment]
Really @remimec? Could you please provide an example of how to reproduce the issue? I'll try to fix it ASAP :hugs:

**Comment by remimec** [comment]
`import investpy
result = investpy.search_quotes(text="stoxx50")[0]
print(result)
print(result.symbol, result.country)
df = investpy.get_stock_historical_data(stock=result.symbol,
                                        country=result.country,
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')
df = investpy.get_index_historical_data(index=result.symbol,
                                        country=result.country,
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')
print(df)`

Not sure if I should use get_stock or get_index, but neither work.

**Comment by alvarobartt** [comment]
Mmm ok so that's not the intended usage of those functions, since using `investpy.search_quotes` is the way you have to access the Investing.com search engine instead of going through the web-scraped CSV files (that are currently outdated). So on, in order to achieve what you are looking for, the code should look like:

```python
import investpy

search_result = investpy.search_quotes(text="stoxx50")
print(search_result)
data = search_result.retrieve_historical_data(from_date="01/01/2010", to_date="01/01/2020")
print(data.head())
```

I really hope this helped you @remimec :hugs: Let me know if you need anything else from my side!

**Comment by matteofr** [comment]
i have a similar problem. am i doing something wrong?

```
import investpy
x = investpy.indices.get_indices_overview('united states')
x.loc[x['name'] == 'S&P 500 VIX']['last'].values[0]
25.42
[x for x in investpy.indices.get_indices_dict() if "V2TX" == x['symbol']][0]
{'country': 'euro zone', 'name': 'STOXX 50 Volatility VSTOXX EUR', 'full_name': 'STOXX 50 Volatility VSTOXX EUR', 'symbol': 'V2TX', 'currency': 'EUR', 'class': 'other_indices', 'market': 'global_indices'}
x = investpy.indices.get_indices_overview('euro zone')
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "..../venv/lib/python3.8/site-packages/investpy/indices.py", line 1013, in get_indices_overview
    raise ConnectionError(
ConnectionError: ERR#0015: error 404, try again later.
```
